name: Build Develop

on:
  pull_request:
    branches: ["develop"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - name: Checkout Build
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --quiet

      - name: Run Unit Tests
        run: yarn test

      - name: Build Project
        run: yarn build

  createPullRequest:
    runs-on: ubuntu-latest
    needs: [build-dev]
    steps:
      - name: Checkout Build
        uses: actions/checkout@v4

      # - name: Make changes to pull request
      #   run: date +%s > report.txt

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHORS

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          branch: develop
          base: ${{ steps.extract_branch.outputs.branch }}
          title: "PR AUTOMATICO >> [${{ steps.extract_branch.outputs.branch }}] to [main]"
          token: ${{ secrets.ACTIONS }}
          commit-message: Update report
          signoff: true
          assignees: ltisistemas
          delete-branch: true
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/ltisistemas/portifolio
